### ISSUE TITLE
其他章节的代码？

### ISSUE THREAD

**Issue by TianHongZXY** [eclipse-du/nlp_book#2]
请问其他章节的代码可否提供？

**Comment by vincentlilee2** [comment]
我是您这本书的读者，但找不到其他章节的书上代码，以及数据下载的链接？可否提供？

**Comment by eclipse-du** [comment]
会陆续提供出来，给您添麻烦了抱歉

**Comment by TianHongZXY** [comment]
好的，谢谢

**Comment by vincentlilee2** [comment]
杜老师，


我在复现第九章代码时，执行小批量训练可以，如果改为训练：
src_strs = codecs.open(pm.src_train, 'r', 'utf-8').read()
trg_strs = codecs.open(pm.tgt_train, 'r', 'utf-8').read()
则执行chatbot时程序回答一律都是（&gt;&gt;[UNK]）。 
拜求老师指点


爱军




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "eclipse-du/nlp_book"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月13日(星期天) 下午2:13
收件人:&nbsp;"eclipse-du/nlp_book"<nlp_book@noreply.github.com&gt;;
抄送:&nbsp;"vincent"<244384154@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [eclipse-du/nlp_book] 其他章节的代码？ (#2)





 
好的，谢谢
